export { default as ContaPage } from './conta/ContaPage'
export { default as HomePage } from './HomePage'
export { default as LoginPage } from './login/LoginPage'
export { default as NovaContaPage } from './login/NovaContaPage'
export { default as SobrePage } from './SobrePage'
export { default as Error } from './Error'
export {default as ModalPage} from './conta/ModalPage'