export { default as ContaPage } from './ContaPage'
export { default as HomePage } from './HomePage'
export { default as LoginPage } from './LoginPage'
export { default as NovaContaPage } from './NovaContaPage'
export { default as SobrePage } from './SobrePage'
export { default as Error } from './Error'
export {default as ModalPage} from './ModalPage'